spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: cris
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
